name: aiworkshop
channels:
  - defaults
dependencies:
  - python=3.6.9
  - jupyter
  - pip:
    - azureml-sdk==1.0.72
    - azure-cognitiveservices-vision-computervision==0.5.0
    - azure-cognitiveservices-vision-customvision==1.0.0
    - keras==2.3.1
    - matplotlib==3.1.2
    - Pillow==6.2.1
    - scikit-learn==0.22
    - tensorflow==2.0.0
    